//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agent.localhost {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShareInformation", Namespace="http://schemas.datacontract.org/2004/07/WallstreetDataService.Model")]
    [System.SerializableAttribute()]
    public partial class ShareInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExchangeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NoOfSharesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PricePerShareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PurchasingVolumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalesVolumeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExchangeName {
            get {
                return this.ExchangeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ExchangeNameField, value) != true)) {
                    this.ExchangeNameField = value;
                    this.RaisePropertyChanged("ExchangeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirmName {
            get {
                return this.FirmNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmNameField, value) != true)) {
                    this.FirmNameField = value;
                    this.RaisePropertyChanged("FirmName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFund {
            get {
                return this.IsFundField;
            }
            set {
                if ((this.IsFundField.Equals(value) != true)) {
                    this.IsFundField = value;
                    this.RaisePropertyChanged("IsFund");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoOfShares {
            get {
                return this.NoOfSharesField;
            }
            set {
                if ((this.NoOfSharesField.Equals(value) != true)) {
                    this.NoOfSharesField = value;
                    this.RaisePropertyChanged("NoOfShares");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PricePerShare {
            get {
                return this.PricePerShareField;
            }
            set {
                if ((this.PricePerShareField.Equals(value) != true)) {
                    this.PricePerShareField = value;
                    this.RaisePropertyChanged("PricePerShare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PurchasingVolume {
            get {
                return this.PurchasingVolumeField;
            }
            set {
                if ((this.PurchasingVolumeField.Equals(value) != true)) {
                    this.PurchasingVolumeField = value;
                    this.RaisePropertyChanged("PurchasingVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SalesVolume {
            get {
                return this.SalesVolumeField;
            }
            set {
                if ((this.SalesVolumeField.Equals(value) != true)) {
                    this.SalesVolumeField = value;
                    this.RaisePropertyChanged("SalesVolume");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvestorDepot", Namespace="http://schemas.datacontract.org/2004/07/WallstreetDataService.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Agent.localhost.FundDepot))]
    public partial class InvestorDepot : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BudgetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExchangeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, int> SharesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Budget {
            get {
                return this.BudgetField;
            }
            set {
                if ((this.BudgetField.Equals(value) != true)) {
                    this.BudgetField = value;
                    this.RaisePropertyChanged("Budget");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExchangeName {
            get {
                return this.ExchangeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ExchangeNameField, value) != true)) {
                    this.ExchangeNameField = value;
                    this.RaisePropertyChanged("ExchangeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, int> Shares {
            get {
                return this.SharesField;
            }
            set {
                if ((object.ReferenceEquals(this.SharesField, value) != true)) {
                    this.SharesField = value;
                    this.RaisePropertyChanged("Shares");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FundDepot", Namespace="http://schemas.datacontract.org/2004/07/WallstreetDataService.Model")]
    [System.SerializableAttribute()]
    public partial class FundDepot : Agent.localhost.InvestorDepot {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvestorRegistration", Namespace="http://schemas.datacontract.org/2004/07/WallstreetDataService.Model")]
    [System.SerializableAttribute()]
    public partial class InvestorRegistration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BudgetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Budget {
            get {
                return this.BudgetField;
            }
            set {
                if ((this.BudgetField.Equals(value) != true)) {
                    this.BudgetField = value;
                    this.RaisePropertyChanged("Budget");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Registration", Namespace="http://schemas.datacontract.org/2004/07/WallstreetDataService.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Agent.localhost.FirmRegistration))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Agent.localhost.FundRegistration))]
    public partial class Registration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SharesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Shares {
            get {
                return this.SharesField;
            }
            set {
                if ((this.SharesField.Equals(value) != true)) {
                    this.SharesField = value;
                    this.RaisePropertyChanged("Shares");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FirmRegistration", Namespace="http://schemas.datacontract.org/2004/07/WallstreetDataService.Model")]
    [System.SerializableAttribute()]
    public partial class FirmRegistration : Agent.localhost.Registration {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PricePerShareField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PricePerShare {
            get {
                return this.PricePerShareField;
            }
            set {
                if ((this.PricePerShareField.Equals(value) != true)) {
                    this.PricePerShareField = value;
                    this.RaisePropertyChanged("PricePerShare");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FundRegistration", Namespace="http://schemas.datacontract.org/2004/07/WallstreetDataService.Model")]
    [System.SerializableAttribute()]
    public partial class FundRegistration : Agent.localhost.Registration {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FundAssetsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FundAssets {
            get {
                return this.FundAssetsField;
            }
            set {
                if ((this.FundAssetsField.Equals(value) != true)) {
                    this.FundAssetsField = value;
                    this.RaisePropertyChanged("FundAssets");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/WallstreetDataService.Model")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvestorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFundShareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NoOfOpenSharesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NoOfProcessedSharesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PrioritizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShareNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Agent.localhost.OrderStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalNoOfSharesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Agent.localhost.OrderType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvestorId {
            get {
                return this.InvestorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.InvestorIdField, value) != true)) {
                    this.InvestorIdField = value;
                    this.RaisePropertyChanged("InvestorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFundShare {
            get {
                return this.IsFundShareField;
            }
            set {
                if ((this.IsFundShareField.Equals(value) != true)) {
                    this.IsFundShareField = value;
                    this.RaisePropertyChanged("IsFundShare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Limit {
            get {
                return this.LimitField;
            }
            set {
                if ((this.LimitField.Equals(value) != true)) {
                    this.LimitField = value;
                    this.RaisePropertyChanged("Limit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoOfOpenShares {
            get {
                return this.NoOfOpenSharesField;
            }
            set {
                if ((this.NoOfOpenSharesField.Equals(value) != true)) {
                    this.NoOfOpenSharesField = value;
                    this.RaisePropertyChanged("NoOfOpenShares");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoOfProcessedShares {
            get {
                return this.NoOfProcessedSharesField;
            }
            set {
                if ((this.NoOfProcessedSharesField.Equals(value) != true)) {
                    this.NoOfProcessedSharesField = value;
                    this.RaisePropertyChanged("NoOfProcessedShares");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Prioritize {
            get {
                return this.PrioritizeField;
            }
            set {
                if ((this.PrioritizeField.Equals(value) != true)) {
                    this.PrioritizeField = value;
                    this.RaisePropertyChanged("Prioritize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShareName {
            get {
                return this.ShareNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShareNameField, value) != true)) {
                    this.ShareNameField = value;
                    this.RaisePropertyChanged("ShareName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Agent.localhost.OrderStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalNoOfShares {
            get {
                return this.TotalNoOfSharesField;
            }
            set {
                if ((this.TotalNoOfSharesField.Equals(value) != true)) {
                    this.TotalNoOfSharesField = value;
                    this.RaisePropertyChanged("TotalNoOfShares");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Agent.localhost.OrderType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderStatus", Namespace="http://schemas.datacontract.org/2004/07/WallstreetDataService.Model")]
    public enum OrderStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OPEN = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PARTIAL = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DONE = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DELETED = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderType", Namespace="http://schemas.datacontract.org/2004/07/WallstreetDataService.Model")]
    public enum OrderType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BUY = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SELL = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://schemas.datacontract.org/2004/07/WallstreetDataService.Model")]
    [System.SerializableAttribute()]
    public partial class Transaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BrokerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuyerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BuyerProvisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuyingOrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FundProvisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NoOfSharesSoldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PricePerShareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PrioritizedBuyingOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PrioritizedSellingOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SellerProvisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellingOrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShareNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BrokerId {
            get {
                return this.BrokerIdField;
            }
            set {
                if ((this.BrokerIdField.Equals(value) != true)) {
                    this.BrokerIdField = value;
                    this.RaisePropertyChanged("BrokerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuyerId {
            get {
                return this.BuyerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BuyerIdField, value) != true)) {
                    this.BuyerIdField = value;
                    this.RaisePropertyChanged("BuyerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BuyerProvision {
            get {
                return this.BuyerProvisionField;
            }
            set {
                if ((this.BuyerProvisionField.Equals(value) != true)) {
                    this.BuyerProvisionField = value;
                    this.RaisePropertyChanged("BuyerProvision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuyingOrderId {
            get {
                return this.BuyingOrderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BuyingOrderIdField, value) != true)) {
                    this.BuyingOrderIdField = value;
                    this.RaisePropertyChanged("BuyingOrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FundProvision {
            get {
                return this.FundProvisionField;
            }
            set {
                if ((this.FundProvisionField.Equals(value) != true)) {
                    this.FundProvisionField = value;
                    this.RaisePropertyChanged("FundProvision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFund {
            get {
                return this.IsFundField;
            }
            set {
                if ((this.IsFundField.Equals(value) != true)) {
                    this.IsFundField = value;
                    this.RaisePropertyChanged("IsFund");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoOfSharesSold {
            get {
                return this.NoOfSharesSoldField;
            }
            set {
                if ((this.NoOfSharesSoldField.Equals(value) != true)) {
                    this.NoOfSharesSoldField = value;
                    this.RaisePropertyChanged("NoOfSharesSold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PricePerShare {
            get {
                return this.PricePerShareField;
            }
            set {
                if ((this.PricePerShareField.Equals(value) != true)) {
                    this.PricePerShareField = value;
                    this.RaisePropertyChanged("PricePerShare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PrioritizedBuyingOrder {
            get {
                return this.PrioritizedBuyingOrderField;
            }
            set {
                if ((this.PrioritizedBuyingOrderField.Equals(value) != true)) {
                    this.PrioritizedBuyingOrderField = value;
                    this.RaisePropertyChanged("PrioritizedBuyingOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PrioritizedSellingOrder {
            get {
                return this.PrioritizedSellingOrderField;
            }
            set {
                if ((this.PrioritizedSellingOrderField.Equals(value) != true)) {
                    this.PrioritizedSellingOrderField = value;
                    this.RaisePropertyChanged("PrioritizedSellingOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SellerId {
            get {
                return this.SellerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SellerIdField, value) != true)) {
                    this.SellerIdField = value;
                    this.RaisePropertyChanged("SellerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SellerProvision {
            get {
                return this.SellerProvisionField;
            }
            set {
                if ((this.SellerProvisionField.Equals(value) != true)) {
                    this.SellerProvisionField = value;
                    this.RaisePropertyChanged("SellerProvision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SellingOrderId {
            get {
                return this.SellingOrderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SellingOrderIdField, value) != true)) {
                    this.SellingOrderIdField = value;
                    this.RaisePropertyChanged("SellingOrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShareName {
            get {
                return this.ShareNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShareNameField, value) != true)) {
                    this.ShareNameField = value;
                    this.RaisePropertyChanged("ShareName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalCost {
            get {
                return this.TotalCostField;
            }
            set {
                if ((this.TotalCostField.Equals(value) != true)) {
                    this.TotalCostField = value;
                    this.RaisePropertyChanged("TotalCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIdField, value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FirmDepot", Namespace="http://schemas.datacontract.org/2004/07/WallstreetDataService.Model")]
    [System.SerializableAttribute()]
    public partial class FirmDepot : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OwnedSharesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirmName {
            get {
                return this.FirmNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmNameField, value) != true)) {
                    this.FirmNameField = value;
                    this.RaisePropertyChanged("FirmName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OwnedShares {
            get {
                return this.OwnedSharesField;
            }
            set {
                if ((this.OwnedSharesField.Equals(value) != true)) {
                    this.OwnedSharesField = value;
                    this.RaisePropertyChanged("OwnedShares");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestResult", Namespace="http://schemas.datacontract.org/2004/07/WallstreetDataService.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Agent.localhost.FundRequestResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Agent.localhost.FirmRequestResult))]
    public partial class RequestResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Agent.localhost.Order OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Agent.localhost.ShareInformation ShareInformationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Agent.localhost.Order Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Agent.localhost.ShareInformation ShareInformation {
            get {
                return this.ShareInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.ShareInformationField, value) != true)) {
                    this.ShareInformationField = value;
                    this.RaisePropertyChanged("ShareInformation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FundRequestResult", Namespace="http://schemas.datacontract.org/2004/07/WallstreetDataService.Model")]
    [System.SerializableAttribute()]
    public partial class FundRequestResult : Agent.localhost.RequestResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Agent.localhost.FundDepot FundDepotField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Agent.localhost.FundDepot FundDepot {
            get {
                return this.FundDepotField;
            }
            set {
                if ((object.ReferenceEquals(this.FundDepotField, value) != true)) {
                    this.FundDepotField = value;
                    this.RaisePropertyChanged("FundDepot");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FirmRequestResult", Namespace="http://schemas.datacontract.org/2004/07/WallstreetDataService.Model")]
    [System.SerializableAttribute()]
    public partial class FirmRequestResult : Agent.localhost.RequestResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Agent.localhost.FirmDepot FirmDepotField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Agent.localhost.FirmDepot FirmDepot {
            get {
                return this.FirmDepotField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmDepotField, value) != true)) {
                    this.FirmDepotField = value;
                    this.RaisePropertyChanged("FirmDepot");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderMatchResult", Namespace="http://schemas.datacontract.org/2004/07/WallstreetDataService.Model")]
    [System.SerializableAttribute()]
    public partial class OrderMatchResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Agent.localhost.Order[] MatchesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Agent.localhost.Order OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Agent.localhost.Transaction[] TransactionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Agent.localhost.Order[] Matches {
            get {
                return this.MatchesField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchesField, value) != true)) {
                    this.MatchesField = value;
                    this.RaisePropertyChanged("Matches");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Agent.localhost.Order Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Agent.localhost.Transaction[] Transactions {
            get {
                return this.TransactionsField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionsField, value) != true)) {
                    this.TransactionsField = value;
                    this.RaisePropertyChanged("Transactions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="localhost.IWallstreetDataService", CallbackContract=typeof(Agent.localhost.IWallstreetDataServiceCallback))]
    public interface IWallstreetDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetExchanges", ReplyAction="http://tempuri.org/IWallstreetDataService/GetExchangesResponse")]
        string[] GetExchanges();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetExchanges", ReplyAction="http://tempuri.org/IWallstreetDataService/GetExchangesResponse")]
        System.Threading.Tasks.Task<string[]> GetExchangesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetMarketInformation", ReplyAction="http://tempuri.org/IWallstreetDataService/GetMarketInformationResponse")]
        Agent.localhost.ShareInformation[] GetMarketInformation(string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetMarketInformation", ReplyAction="http://tempuri.org/IWallstreetDataService/GetMarketInformationResponse")]
        System.Threading.Tasks.Task<Agent.localhost.ShareInformation[]> GetMarketInformationAsync(string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetOverallMarketInformation", ReplyAction="http://tempuri.org/IWallstreetDataService/GetOverallMarketInformationResponse")]
        Agent.localhost.ShareInformation[] GetOverallMarketInformation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetOverallMarketInformation", ReplyAction="http://tempuri.org/IWallstreetDataService/GetOverallMarketInformationResponse")]
        System.Threading.Tasks.Task<Agent.localhost.ShareInformation[]> GetOverallMarketInformationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetShareInformation", ReplyAction="http://tempuri.org/IWallstreetDataService/GetShareInformationResponse")]
        Agent.localhost.ShareInformation GetShareInformation(string shareName, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetShareInformation", ReplyAction="http://tempuri.org/IWallstreetDataService/GetShareInformationResponse")]
        System.Threading.Tasks.Task<Agent.localhost.ShareInformation> GetShareInformationAsync(string shareName, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/PutShareInformation")]
        void PutShareInformation(Agent.localhost.ShareInformation info, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/PutShareInformation")]
        System.Threading.Tasks.Task PutShareInformationAsync(Agent.localhost.ShareInformation info, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetInvestorInformation", ReplyAction="http://tempuri.org/IWallstreetDataService/GetInvestorInformationResponse")]
        Agent.localhost.InvestorDepot[] GetInvestorInformation(string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetInvestorInformation", ReplyAction="http://tempuri.org/IWallstreetDataService/GetInvestorInformationResponse")]
        System.Threading.Tasks.Task<Agent.localhost.InvestorDepot[]> GetInvestorInformationAsync(string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetInvestorDepot", ReplyAction="http://tempuri.org/IWallstreetDataService/GetInvestorDepotResponse")]
        Agent.localhost.InvestorDepot GetInvestorDepot(string investorId, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetInvestorDepot", ReplyAction="http://tempuri.org/IWallstreetDataService/GetInvestorDepotResponse")]
        System.Threading.Tasks.Task<Agent.localhost.InvestorDepot> GetInvestorDepotAsync(string investorId, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/PutInvestorDepot")]
        void PutInvestorDepot(Agent.localhost.InvestorDepot investor, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/PutInvestorDepot")]
        System.Threading.Tasks.Task PutInvestorDepotAsync(Agent.localhost.InvestorDepot investor, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/LoginInvestor", ReplyAction="http://tempuri.org/IWallstreetDataService/LoginInvestorResponse")]
        Agent.localhost.InvestorDepot LoginInvestor(Agent.localhost.InvestorRegistration registration, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/LoginInvestor", ReplyAction="http://tempuri.org/IWallstreetDataService/LoginInvestorResponse")]
        System.Threading.Tasks.Task<Agent.localhost.InvestorDepot> LoginInvestorAsync(Agent.localhost.InvestorRegistration registration, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetRegisteredExchanges", ReplyAction="http://tempuri.org/IWallstreetDataService/GetRegisteredExchangesResponse")]
        string[] GetRegisteredExchanges(string investorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetRegisteredExchanges", ReplyAction="http://tempuri.org/IWallstreetDataService/GetRegisteredExchangesResponse")]
        System.Threading.Tasks.Task<string[]> GetRegisteredExchangesAsync(string investorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetFundDepot", ReplyAction="http://tempuri.org/IWallstreetDataService/GetFundDepotResponse")]
        Agent.localhost.FundDepot GetFundDepot(string fundId, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetFundDepot", ReplyAction="http://tempuri.org/IWallstreetDataService/GetFundDepotResponse")]
        System.Threading.Tasks.Task<Agent.localhost.FundDepot> GetFundDepotAsync(string fundId, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetOverallFundInformation", ReplyAction="http://tempuri.org/IWallstreetDataService/GetOverallFundInformationResponse")]
        Agent.localhost.FundDepot GetOverallFundInformation(string fundId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetOverallFundInformation", ReplyAction="http://tempuri.org/IWallstreetDataService/GetOverallFundInformationResponse")]
        System.Threading.Tasks.Task<Agent.localhost.FundDepot> GetOverallFundInformationAsync(string fundId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/LoginFund")]
        void LoginFund(Agent.localhost.FundRegistration registration, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/LoginFund")]
        System.Threading.Tasks.Task LoginFundAsync(Agent.localhost.FundRegistration registration, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetOrders", ReplyAction="http://tempuri.org/IWallstreetDataService/GetOrdersResponse")]
        Agent.localhost.Order[] GetOrders(string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetOrders", ReplyAction="http://tempuri.org/IWallstreetDataService/GetOrdersResponse")]
        System.Threading.Tasks.Task<Agent.localhost.Order[]> GetOrdersAsync(string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetOverallOrders", ReplyAction="http://tempuri.org/IWallstreetDataService/GetOverallOrdersResponse")]
        Agent.localhost.Order[] GetOverallOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetOverallOrders", ReplyAction="http://tempuri.org/IWallstreetDataService/GetOverallOrdersResponse")]
        System.Threading.Tasks.Task<Agent.localhost.Order[]> GetOverallOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetPendingOrders", ReplyAction="http://tempuri.org/IWallstreetDataService/GetPendingOrdersResponse")]
        Agent.localhost.Order[] GetPendingOrders(string investorId, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetPendingOrders", ReplyAction="http://tempuri.org/IWallstreetDataService/GetPendingOrdersResponse")]
        System.Threading.Tasks.Task<Agent.localhost.Order[]> GetPendingOrdersAsync(string investorId, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/PutOrder")]
        void PutOrder(Agent.localhost.Order order, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/PutOrder")]
        System.Threading.Tasks.Task PutOrderAsync(Agent.localhost.Order order, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/DeleteOrder")]
        void DeleteOrder(Agent.localhost.Order order, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/DeleteOrder")]
        System.Threading.Tasks.Task DeleteOrderAsync(Agent.localhost.Order order, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetTransactions", ReplyAction="http://tempuri.org/IWallstreetDataService/GetTransactionsResponse")]
        Agent.localhost.Transaction[] GetTransactions(string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetTransactions", ReplyAction="http://tempuri.org/IWallstreetDataService/GetTransactionsResponse")]
        System.Threading.Tasks.Task<Agent.localhost.Transaction[]> GetTransactionsAsync(string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/PutTransaction")]
        void PutTransaction(Agent.localhost.Transaction transaction, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/PutTransaction")]
        System.Threading.Tasks.Task PutTransactionAsync(Agent.localhost.Transaction transaction, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/RegisterFirm", ReplyAction="http://tempuri.org/IWallstreetDataService/RegisterFirmResponse")]
        Agent.localhost.FirmDepot RegisterFirm(Agent.localhost.FirmRegistration request, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/RegisterFirm", ReplyAction="http://tempuri.org/IWallstreetDataService/RegisterFirmResponse")]
        System.Threading.Tasks.Task<Agent.localhost.FirmDepot> RegisterFirmAsync(Agent.localhost.FirmRegistration request, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetFirmDepot", ReplyAction="http://tempuri.org/IWallstreetDataService/GetFirmDepotResponse")]
        Agent.localhost.FirmDepot GetFirmDepot(string firmName, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWallstreetDataService/GetFirmDepot", ReplyAction="http://tempuri.org/IWallstreetDataService/GetFirmDepotResponse")]
        System.Threading.Tasks.Task<Agent.localhost.FirmDepot> GetFirmDepotAsync(string firmName, string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/SubscribeOnNewShareInformationAvailable" +
            "")]
        void SubscribeOnNewShareInformationAvailable(string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/SubscribeOnNewShareInformationAvailable" +
            "")]
        System.Threading.Tasks.Task SubscribeOnNewShareInformationAvailableAsync(string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/SubscribeOnNewFundDepotAvailable")]
        void SubscribeOnNewFundDepotAvailable(string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/SubscribeOnNewFundDepotAvailable")]
        System.Threading.Tasks.Task SubscribeOnNewFundDepotAvailableAsync(string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/SubscribeOnNewOrderAvailable")]
        void SubscribeOnNewOrderAvailable(string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/SubscribeOnNewOrderAvailable")]
        System.Threading.Tasks.Task SubscribeOnNewOrderAvailableAsync(string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/SubscribeOnNewInvestorDepotAvailable")]
        void SubscribeOnNewInvestorDepotAvailable(string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/SubscribeOnNewInvestorDepotAvailable")]
        System.Threading.Tasks.Task SubscribeOnNewInvestorDepotAvailableAsync(string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/SubscribeOnNewTransactionAvailable")]
        void SubscribeOnNewTransactionAvailable(string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/SubscribeOnNewTransactionAvailable")]
        System.Threading.Tasks.Task SubscribeOnNewTransactionAvailableAsync(string exchangeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWallstreetDataServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/OnNewInvestorDepotAvailable")]
        void OnNewInvestorDepotAvailable(Agent.localhost.InvestorDepot depot);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/OnNewFundDepotAvailable")]
        void OnNewFundDepotAvailable(Agent.localhost.FundDepot depot);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/OnNewShareInformationAvailable")]
        void OnNewShareInformationAvailable(Agent.localhost.ShareInformation info);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/OnNewOrderAvailable")]
        void OnNewOrderAvailable(Agent.localhost.Order order);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWallstreetDataService/OnNewTransactionAvailable")]
        void OnNewTransactionAvailable(Agent.localhost.Transaction transaction);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWallstreetDataServiceChannel : Agent.localhost.IWallstreetDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WallstreetDataServiceClient : System.ServiceModel.DuplexClientBase<Agent.localhost.IWallstreetDataService>, Agent.localhost.IWallstreetDataService {
        
        public WallstreetDataServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public WallstreetDataServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public WallstreetDataServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WallstreetDataServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WallstreetDataServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public string[] GetExchanges() {
            return base.Channel.GetExchanges();
        }
        
        public System.Threading.Tasks.Task<string[]> GetExchangesAsync() {
            return base.Channel.GetExchangesAsync();
        }
        
        public Agent.localhost.ShareInformation[] GetMarketInformation(string exchangeId) {
            return base.Channel.GetMarketInformation(exchangeId);
        }
        
        public System.Threading.Tasks.Task<Agent.localhost.ShareInformation[]> GetMarketInformationAsync(string exchangeId) {
            return base.Channel.GetMarketInformationAsync(exchangeId);
        }
        
        public Agent.localhost.ShareInformation[] GetOverallMarketInformation() {
            return base.Channel.GetOverallMarketInformation();
        }
        
        public System.Threading.Tasks.Task<Agent.localhost.ShareInformation[]> GetOverallMarketInformationAsync() {
            return base.Channel.GetOverallMarketInformationAsync();
        }
        
        public Agent.localhost.ShareInformation GetShareInformation(string shareName, string exchangeId) {
            return base.Channel.GetShareInformation(shareName, exchangeId);
        }
        
        public System.Threading.Tasks.Task<Agent.localhost.ShareInformation> GetShareInformationAsync(string shareName, string exchangeId) {
            return base.Channel.GetShareInformationAsync(shareName, exchangeId);
        }
        
        public void PutShareInformation(Agent.localhost.ShareInformation info, string exchangeId) {
            base.Channel.PutShareInformation(info, exchangeId);
        }
        
        public System.Threading.Tasks.Task PutShareInformationAsync(Agent.localhost.ShareInformation info, string exchangeId) {
            return base.Channel.PutShareInformationAsync(info, exchangeId);
        }
        
        public Agent.localhost.InvestorDepot[] GetInvestorInformation(string exchangeId) {
            return base.Channel.GetInvestorInformation(exchangeId);
        }
        
        public System.Threading.Tasks.Task<Agent.localhost.InvestorDepot[]> GetInvestorInformationAsync(string exchangeId) {
            return base.Channel.GetInvestorInformationAsync(exchangeId);
        }
        
        public Agent.localhost.InvestorDepot GetInvestorDepot(string investorId, string exchangeId) {
            return base.Channel.GetInvestorDepot(investorId, exchangeId);
        }
        
        public System.Threading.Tasks.Task<Agent.localhost.InvestorDepot> GetInvestorDepotAsync(string investorId, string exchangeId) {
            return base.Channel.GetInvestorDepotAsync(investorId, exchangeId);
        }
        
        public void PutInvestorDepot(Agent.localhost.InvestorDepot investor, string exchangeId) {
            base.Channel.PutInvestorDepot(investor, exchangeId);
        }
        
        public System.Threading.Tasks.Task PutInvestorDepotAsync(Agent.localhost.InvestorDepot investor, string exchangeId) {
            return base.Channel.PutInvestorDepotAsync(investor, exchangeId);
        }
        
        public Agent.localhost.InvestorDepot LoginInvestor(Agent.localhost.InvestorRegistration registration, string exchangeId) {
            return base.Channel.LoginInvestor(registration, exchangeId);
        }
        
        public System.Threading.Tasks.Task<Agent.localhost.InvestorDepot> LoginInvestorAsync(Agent.localhost.InvestorRegistration registration, string exchangeId) {
            return base.Channel.LoginInvestorAsync(registration, exchangeId);
        }
        
        public string[] GetRegisteredExchanges(string investorId) {
            return base.Channel.GetRegisteredExchanges(investorId);
        }
        
        public System.Threading.Tasks.Task<string[]> GetRegisteredExchangesAsync(string investorId) {
            return base.Channel.GetRegisteredExchangesAsync(investorId);
        }
        
        public Agent.localhost.FundDepot GetFundDepot(string fundId, string exchangeId) {
            return base.Channel.GetFundDepot(fundId, exchangeId);
        }
        
        public System.Threading.Tasks.Task<Agent.localhost.FundDepot> GetFundDepotAsync(string fundId, string exchangeId) {
            return base.Channel.GetFundDepotAsync(fundId, exchangeId);
        }
        
        public Agent.localhost.FundDepot GetOverallFundInformation(string fundId) {
            return base.Channel.GetOverallFundInformation(fundId);
        }
        
        public System.Threading.Tasks.Task<Agent.localhost.FundDepot> GetOverallFundInformationAsync(string fundId) {
            return base.Channel.GetOverallFundInformationAsync(fundId);
        }
        
        public void LoginFund(Agent.localhost.FundRegistration registration, string exchangeId) {
            base.Channel.LoginFund(registration, exchangeId);
        }
        
        public System.Threading.Tasks.Task LoginFundAsync(Agent.localhost.FundRegistration registration, string exchangeId) {
            return base.Channel.LoginFundAsync(registration, exchangeId);
        }
        
        public Agent.localhost.Order[] GetOrders(string exchangeId) {
            return base.Channel.GetOrders(exchangeId);
        }
        
        public System.Threading.Tasks.Task<Agent.localhost.Order[]> GetOrdersAsync(string exchangeId) {
            return base.Channel.GetOrdersAsync(exchangeId);
        }
        
        public Agent.localhost.Order[] GetOverallOrders() {
            return base.Channel.GetOverallOrders();
        }
        
        public System.Threading.Tasks.Task<Agent.localhost.Order[]> GetOverallOrdersAsync() {
            return base.Channel.GetOverallOrdersAsync();
        }
        
        public Agent.localhost.Order[] GetPendingOrders(string investorId, string exchangeId) {
            return base.Channel.GetPendingOrders(investorId, exchangeId);
        }
        
        public System.Threading.Tasks.Task<Agent.localhost.Order[]> GetPendingOrdersAsync(string investorId, string exchangeId) {
            return base.Channel.GetPendingOrdersAsync(investorId, exchangeId);
        }
        
        public void PutOrder(Agent.localhost.Order order, string exchangeId) {
            base.Channel.PutOrder(order, exchangeId);
        }
        
        public System.Threading.Tasks.Task PutOrderAsync(Agent.localhost.Order order, string exchangeId) {
            return base.Channel.PutOrderAsync(order, exchangeId);
        }
        
        public void DeleteOrder(Agent.localhost.Order order, string exchangeId) {
            base.Channel.DeleteOrder(order, exchangeId);
        }
        
        public System.Threading.Tasks.Task DeleteOrderAsync(Agent.localhost.Order order, string exchangeId) {
            return base.Channel.DeleteOrderAsync(order, exchangeId);
        }
        
        public Agent.localhost.Transaction[] GetTransactions(string exchangeId) {
            return base.Channel.GetTransactions(exchangeId);
        }
        
        public System.Threading.Tasks.Task<Agent.localhost.Transaction[]> GetTransactionsAsync(string exchangeId) {
            return base.Channel.GetTransactionsAsync(exchangeId);
        }
        
        public void PutTransaction(Agent.localhost.Transaction transaction, string exchangeId) {
            base.Channel.PutTransaction(transaction, exchangeId);
        }
        
        public System.Threading.Tasks.Task PutTransactionAsync(Agent.localhost.Transaction transaction, string exchangeId) {
            return base.Channel.PutTransactionAsync(transaction, exchangeId);
        }
        
        public Agent.localhost.FirmDepot RegisterFirm(Agent.localhost.FirmRegistration request, string exchangeId) {
            return base.Channel.RegisterFirm(request, exchangeId);
        }
        
        public System.Threading.Tasks.Task<Agent.localhost.FirmDepot> RegisterFirmAsync(Agent.localhost.FirmRegistration request, string exchangeId) {
            return base.Channel.RegisterFirmAsync(request, exchangeId);
        }
        
        public Agent.localhost.FirmDepot GetFirmDepot(string firmName, string exchangeId) {
            return base.Channel.GetFirmDepot(firmName, exchangeId);
        }
        
        public System.Threading.Tasks.Task<Agent.localhost.FirmDepot> GetFirmDepotAsync(string firmName, string exchangeId) {
            return base.Channel.GetFirmDepotAsync(firmName, exchangeId);
        }
        
        public void SubscribeOnNewShareInformationAvailable(string exchangeId) {
            base.Channel.SubscribeOnNewShareInformationAvailable(exchangeId);
        }
        
        public System.Threading.Tasks.Task SubscribeOnNewShareInformationAvailableAsync(string exchangeId) {
            return base.Channel.SubscribeOnNewShareInformationAvailableAsync(exchangeId);
        }
        
        public void SubscribeOnNewFundDepotAvailable(string exchangeId) {
            base.Channel.SubscribeOnNewFundDepotAvailable(exchangeId);
        }
        
        public System.Threading.Tasks.Task SubscribeOnNewFundDepotAvailableAsync(string exchangeId) {
            return base.Channel.SubscribeOnNewFundDepotAvailableAsync(exchangeId);
        }
        
        public void SubscribeOnNewOrderAvailable(string exchangeId) {
            base.Channel.SubscribeOnNewOrderAvailable(exchangeId);
        }
        
        public System.Threading.Tasks.Task SubscribeOnNewOrderAvailableAsync(string exchangeId) {
            return base.Channel.SubscribeOnNewOrderAvailableAsync(exchangeId);
        }
        
        public void SubscribeOnNewInvestorDepotAvailable(string exchangeId) {
            base.Channel.SubscribeOnNewInvestorDepotAvailable(exchangeId);
        }
        
        public System.Threading.Tasks.Task SubscribeOnNewInvestorDepotAvailableAsync(string exchangeId) {
            return base.Channel.SubscribeOnNewInvestorDepotAvailableAsync(exchangeId);
        }
        
        public void SubscribeOnNewTransactionAvailable(string exchangeId) {
            base.Channel.SubscribeOnNewTransactionAvailable(exchangeId);
        }
        
        public System.Threading.Tasks.Task SubscribeOnNewTransactionAvailableAsync(string exchangeId) {
            return base.Channel.SubscribeOnNewTransactionAvailableAsync(exchangeId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="localhost.IBrokerService", CallbackContract=typeof(Agent.localhost.IBrokerServiceCallback))]
    public interface IBrokerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/RegisterBroker", ReplyAction="http://tempuri.org/IBrokerService/RegisterBrokerResponse")]
        void RegisterBroker(string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/RegisterBroker", ReplyAction="http://tempuri.org/IBrokerService/RegisterBrokerResponse")]
        System.Threading.Tasks.Task RegisterBrokerAsync(string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/UnregisterBroker", ReplyAction="http://tempuri.org/IBrokerService/UnregisterBrokerResponse")]
        void UnregisterBroker(string exchangeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/UnregisterBroker", ReplyAction="http://tempuri.org/IBrokerService/UnregisterBrokerResponse")]
        System.Threading.Tasks.Task UnregisterBrokerAsync(string exchangeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBrokerServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/ProcessFirmRegistration", ReplyAction="http://tempuri.org/IBrokerService/ProcessFirmRegistrationResponse")]
        Agent.localhost.FirmRequestResult ProcessFirmRegistration(Agent.localhost.FirmRegistration request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/ProcessFundRegistration", ReplyAction="http://tempuri.org/IBrokerService/ProcessFundRegistrationResponse")]
        Agent.localhost.FundRequestResult ProcessFundRegistration(Agent.localhost.FundRegistration request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/ProcessMatchingOrders", ReplyAction="http://tempuri.org/IBrokerService/ProcessMatchingOrdersResponse")]
        Agent.localhost.OrderMatchResult ProcessMatchingOrders(Agent.localhost.Order order, Agent.localhost.Order[] orders);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBrokerServiceChannel : Agent.localhost.IBrokerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BrokerServiceClient : System.ServiceModel.DuplexClientBase<Agent.localhost.IBrokerService>, Agent.localhost.IBrokerService {
        
        public BrokerServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public BrokerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public BrokerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public BrokerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public BrokerServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void RegisterBroker(string exchangeId) {
            base.Channel.RegisterBroker(exchangeId);
        }
        
        public System.Threading.Tasks.Task RegisterBrokerAsync(string exchangeId) {
            return base.Channel.RegisterBrokerAsync(exchangeId);
        }
        
        public void UnregisterBroker(string exchangeId) {
            base.Channel.UnregisterBroker(exchangeId);
        }
        
        public System.Threading.Tasks.Task UnregisterBrokerAsync(string exchangeId) {
            return base.Channel.UnregisterBrokerAsync(exchangeId);
        }
    }
}
